### PR TITLE
Few bug fixes introduced by last update

### PR DESCRIPTION
**Pull request by jlmaurer**
- adds missing imports, fixes typing issues

### CODE REVIEW

**Comment by jlmaurer** [comment]
@bbuzz31 @dbekaert @jhkennedy this should fix both the python version bug and the import bugs.

**Comment by jlmaurer** [comment]
Suggest we release this as a patch.

**Review by jhkennedy — CHANGES_REQUESTED** [review]
We're really close -- all the imports work, and all the entry points work on 3.10. Same for 3.9 now, except for:
```
raider.py -h                                       ✔  11:52:00
Traceback (most recent call last):
  File "/home/jhkennedy/mambaforge/envs/RAiDER-test/bin/raider.py", line 8, in <module>
    sys.exit(main())
  File "/home/jhkennedy/Documents/Code/contributing/RAiDER/tools/RAiDER/cli/__main__.py", line 20, in main
    process_entry_point = entry_points(group='console_scripts', name=f'{args.process}.py')[0]
TypeError: entry_points() got an unexpected keyword argument 'group'
```

Also using the python 3.10 interface for this... I'll push a change

**Review by jhkennedy — APPROVED** [review]

**Review by bbuzz31 — APPROVED** [review]

**Review by bbuzz31 — DISMISSED** [review]
@jlmaurer could you add a fix for  #453

**Comment by jhkennedy** [comment]
@bbuzz31 #453 are fixed here.

**Review by bbuzz31 — APPROVED** [review]
